spring:
  application:
    name: tlias-web-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept
    username: root
    password: 727272Ptx
  servlet:
    multipart:
      max-file-size: 10MB #最大单个文件大小
      max-request-size: 100MB #最大请求文件大小（包括所有文件和表单数据）

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-aiptx
    region: cn-beijing

